#ifndef WIN32PROCESSEXPLORER_GLOBAL_H
#define WIN32PROCESSEXPLORER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIN32PROCESSEXPLORER_LIBRARY)
#  define WIN32PROCESSEXPLORERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIN32PROCESSEXPLORERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIN32PROCESSEXPLORER_GLOBAL_H
